### PR TITLE
Reword the documentation about warning leak to make it clearer

### PR DESCRIPTION
**Pull request by perlancar**
Ref: issue #2

### CODE REVIEW

**Review by FGasper — CHANGES_REQUESTED** [review]
It isn't necessary to use "my"; you can also just clean up global instances; e.g., in an END block.

Since strict mode enforces "my" anyway I'm hesitant to include that.

**Comment by perlancar** [comment]
I guess I'll leave it to you to formulate the exact wording. My suggestion is to add a conjunction between the two sentences, e.g. "Also, avoid circular references" so it's clearer to reader (like me) that the two sentences are talking about different issue. Thank you.

**Comment by FGasper** [comment]
@perlancar How does the wording in my own PR strike you?

**Comment by perlancar** [comment]
> @perlancar How does the wording in my own PR strike you?

That's better than the original text. Thanks!

**Pull request closed without merging**
